/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsSchedulesRouteImport } from './routes/settings.schedules'
import { Route as SettingsAgentsRouteImport } from './routes/settings.agents'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSchedulesRoute = SettingsSchedulesRouteImport.update({
  id: '/settings/schedules',
  path: '/settings/schedules',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAgentsRoute = SettingsAgentsRouteImport.update({
  id: '/settings/agents',
  path: '/settings/agents',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings/agents': typeof SettingsAgentsRoute
  '/settings/schedules': typeof SettingsSchedulesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings/agents': typeof SettingsAgentsRoute
  '/settings/schedules': typeof SettingsSchedulesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings/agents': typeof SettingsAgentsRoute
  '/settings/schedules': typeof SettingsSchedulesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/settings/agents' | '/settings/schedules'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/settings/agents' | '/settings/schedules'
  id: '__root__' | '/' | '/login' | '/settings/agents' | '/settings/schedules'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SettingsAgentsRoute: typeof SettingsAgentsRoute
  SettingsSchedulesRoute: typeof SettingsSchedulesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/schedules': {
      id: '/settings/schedules'
      path: '/settings/schedules'
      fullPath: '/settings/schedules'
      preLoaderRoute: typeof SettingsSchedulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/agents': {
      id: '/settings/agents'
      path: '/settings/agents'
      fullPath: '/settings/agents'
      preLoaderRoute: typeof SettingsAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SettingsAgentsRoute: SettingsAgentsRoute,
  SettingsSchedulesRoute: SettingsSchedulesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
